#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 03, 2018 09:52:30 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Main_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Main (root)
    Main_support.init(root, top)
    root.mainloop()

w = None
def create_Main(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Main (w)
    Main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Main():
    global w
    w.destroy()
    w = None


class Main:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1024x700+403+207")
        top.title("Main")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.frmMenuBar = Frame(top)
        self.frmMenuBar.place(relx=0.0, rely=0.0, relheight=0.06, relwidth=1.0)
        self.frmMenuBar.configure(relief=GROOVE)
        self.frmMenuBar.configure(borderwidth="2")
        self.frmMenuBar.configure(relief=GROOVE)
        self.frmMenuBar.configure(background="#d9d9d9")
        self.frmMenuBar.configure(highlightbackground="#d9d9d9")
        self.frmMenuBar.configure(highlightcolor="black")
        self.frmMenuBar.configure(width=125)

        self.tbtnExit = ttk.Button(self.frmMenuBar)
        self.tbtnExit.place(relx=0.96, rely=0.1, height=32, width=32)
        self.tbtnExit.configure(command=Main_support.mbExit)
        self.tbtnExit.configure(takefocus="")
        self.tbtnExit.configure(text='''Tbutton''')
        self._img1 = PhotoImage(file="./graphics/application-exit.png")
        self.tbtnExit.configure(image=self._img1)

        self.tbtnFileOpen = ttk.Button(self.frmMenuBar)
        self.tbtnFileOpen.place(relx=0.04, rely=0.1, height=32, width=32)
        self.tbtnFileOpen.configure(command=Main_support.mbFileOpen)
        self.tbtnFileOpen.configure(takefocus="")
        self.tbtnFileOpen.configure(text='''Tbutton''')
        self._img2 = PhotoImage(file="./graphics/document-open.png")
        self.tbtnFileOpen.configure(image=self._img2)

        self.tbtnFileNew = ttk.Button(self.frmMenuBar)
        self.tbtnFileNew.place(relx=0.0, rely=0.1, height=32, width=32)
        self.tbtnFileNew.configure(command=Main_support.mbFileNew)
        self.tbtnFileNew.configure(takefocus="")
        self.tbtnFileNew.configure(text='''Tbutton''')
        self._img3 = PhotoImage(file="./graphics/document-new.png")
        self.tbtnFileNew.configure(image=self._img3)

        self.tbtnCopy = ttk.Button(self.frmMenuBar)
        self.tbtnCopy.place(relx=0.14, rely=0.1, height=32, width=32)
        self.tbtnCopy.configure(command=Main_support.mbCopy)
        self.tbtnCopy.configure(takefocus="")
        self.tbtnCopy.configure(text='''Tbutton''')
        self._img4 = PhotoImage(file="./graphics/edit-copy.png")
        self.tbtnCopy.configure(image=self._img4)

        self.tbtnPaste = ttk.Button(self.frmMenuBar)
        self.tbtnPaste.place(relx=0.2, rely=0.1, height=32, width=32)
        self.tbtnPaste.configure(command=Main_support.mbPaste)
        self.tbtnPaste.configure(takefocus="")
        self.tbtnPaste.configure(text='''Tbutton''')
        self._img5 = PhotoImage(file="./graphics/edit-paste.png")
        self.tbtnPaste.configure(image=self._img5)

        self.tbtnAbout = ttk.Button(self.frmMenuBar)
        self.tbtnAbout.place(relx=0.91, rely=0.1, height=32, width=32)
        self.tbtnAbout.configure(command=Main_support.mbAbout)
        self.tbtnAbout.configure(takefocus="")
        self.tbtnAbout.configure(text='''Tbutton''')
        self._img6 = PhotoImage(file="./graphics/help-about.png")
        self.tbtnAbout.configure(image=self._img6)

        self.tbtnCut = ttk.Button(self.frmMenuBar)
        self.tbtnCut.place(relx=0.17, rely=0.1, height=32, width=32)
        self.tbtnCut.configure(command=Main_support.mbCut)
        self.tbtnCut.configure(takefocus="")
        self.tbtnCut.configure(text='''Tbutton''')
        self._img7 = PhotoImage(file="./graphics/edit-cut.png")
        self.tbtnCut.configure(image=self._img7)

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.01, rely=0.07, relheight=0.92, relwidth=0.37)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=375)

        self.Frame3 = Frame(top)
        self.Frame3.place(relx=0.38, rely=0.07, relheight=0.52, relwidth=0.61)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")
        self.Frame3.configure(width=625)

        self.Frame4 = Frame(top)
        self.Frame4.place(relx=0.38, rely=0.6, relheight=0.39, relwidth=0.61)
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(background="#d9d9d9")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")
        self.Frame4.configure(width=625)






if __name__ == '__main__':
    vp_start_gui()



