#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics application-exit.png]} {user image} user {}}
        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics document-new.png]} {user image} user {}}
        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics document-open.png]} {user image} user {}}
        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics edit-copy.png]} {user image} user {}}
        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics edit-cut.png]} {user image} user {}}
        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics edit-paste.png]} {user image} user {}}
        {{[file join / home greg Desktop PageBook splash Splashtest1 graphics help-about.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1024x700+403+207
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 770
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Main"
    vTcl:DefineAlias "$top" "tlMain" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra38" "frmMenuBar" vTcl:WidgetProc "tlMain" 1
    set site_3_0 $top.fra38
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu39 \
        -command mbExit -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics application-exit.png]] 
    vTcl:DefineAlias "$site_3_0.tBu39" "tbtnExit" vTcl:WidgetProc "tlMain" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu40 \
        -command mbFileOpen -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics document-open.png]] 
    vTcl:DefineAlias "$site_3_0.tBu40" "tbtnFileOpen" vTcl:WidgetProc "tlMain" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu41 \
        -command mbFileNew -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics document-new.png]] 
    vTcl:DefineAlias "$site_3_0.tBu41" "tbtnFileNew" vTcl:WidgetProc "tlMain" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu42 \
        -command mbCopy -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics edit-copy.png]] 
    vTcl:DefineAlias "$site_3_0.tBu42" "tbtnCopy" vTcl:WidgetProc "tlMain" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu43 \
        -command mbPaste -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics edit-paste.png]] 
    vTcl:DefineAlias "$site_3_0.tBu43" "tbtnPaste" vTcl:WidgetProc "tlMain" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu44 \
        -command mbAbout -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics help-about.png]] 
    vTcl:DefineAlias "$site_3_0.tBu44" "tbtnAbout" vTcl:WidgetProc "tlMain" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu45 \
        -command mbCut -takefocus {} -text Tbutton \
        -image [vTcl:image:get_image [file join / home greg Desktop PageBook splash Splashtest1 graphics edit-cut.png]] 
    vTcl:DefineAlias "$site_3_0.tBu45" "tbtnCut" vTcl:WidgetProc "tlMain" 1
    place $site_3_0.tBu39 \
        -in $site_3_0 -x 980 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu40 \
        -in $site_3_0 -x 42 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu41 \
        -in $site_3_0 -x 5 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu42 \
        -in $site_3_0 -x 140 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu43 \
        -in $site_3_0 -x 208 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu44 \
        -in $site_3_0 -x 930 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu45 \
        -in $site_3_0 -x 174 -y 4 -width 32 -height 32 -anchor nw \
        -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 645 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 375 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "tlMain" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 365 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 625 
    vTcl:DefineAlias "$top.fra47" "Frame3" vTcl:WidgetProc "tlMain" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 275 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 625 
    vTcl:DefineAlias "$top.fra48" "Frame4" vTcl:WidgetProc "tlMain" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 2 -y 2 -width 1020 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 10 -y 50 -width 375 -relwidth 0 -height 645 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 390 -y 50 -width 625 -relwidth 0 -height 365 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 390 -y 420 -width 625 -relwidth 0 -height 275 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

