#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11f
# In conjunction with Tcl version 8.6
#    Mar 05, 2018 11:13:07 AM
#======================================================
#              splash1.py
#------------------------------------------------------
# Created for the Learning Page Book Project
# Written by G.D. Walters
# Copyright (c) 2018 by G.D. Walters
# This source code is released under the MIT License
# (See MIT_License.txt)
#======================================================
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import splash1_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Splash(root)
    splash1_support.init(root, top)
    root.mainloop()

w = None


def create_Splash(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = Splash(w)
    splash1_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Splash():
    global w
    w.destroy()
    w = None


class Splash:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
            self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map(
            '.', background=
            [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("600x405+294+144")
        top.title("Splash")
        top.configure(highlightcolor="black")

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(relx=0.0, rely=-0.1, height=490, width=600)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(anchor=CENTER)
        self.TLabel1.configure(justify=CENTER)
        self.TLabel1.configure(width=600)


if __name__ == '__main__':
    vp_start_gui()
